# Generated by Django 2.0 on 2018-08-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180817_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '账号表'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='menu',
            new_name='menus',
        ),
    ]
