# Generated by Django 2.0 on 2018-08-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180818_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '客户表'},
        ),
    ]
